version: "3"
services:
  postgres-todo-list:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-todo-list
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-list
  # APP*****************************************
  springbootapp:
    image: todo-list-app:latest
    network_mode: bridge
    container_name: todo-list-app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres-todo-list
    links:
      - postgres-todo-list