CREATE TABLE TDL_TAREFA (
    ID bigint NOT NULL,
    ID_USUARIO bigint NOT NULL,
    RESUMO varchar(255) NULL,
    DESCRICAO varchar(2000) NOT NULL,
    CODIGO_STATUS int NOT NULL,
    DATA_INCLUSAO timestamp NOT NULL,
    DATA_ALTERACAO timestamp NOT NULL,

    CONSTRAINT TDL_TAREFA_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES TDL_USUARIO (ID)
);

CREATE INDEX IDX_TDL_TAREFA_ID_USUARIO ON TDL_TAREFA (ID_USUARIO);

CREATE SEQUENCE SEQ_TDL_TAREFA
    INCREMENT 10
    MINVALUE 10
    MAXVALUE 9223372036854775807
    START 10
    CACHE 1;